[project]
name = "assistant-bot"
version = "0.1.0"
description = "CLI assistant bot for managing contacts and notes"
readme = "README.md"
requires-python = ">=3.10"

authors = [
    { name = "Drevo Team" }
]

dependencies = [
    "tabulate"
]

[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["assistant_bot*"]

[project.scripts]
assistant-bot = "assistant_bot.main:main"